name: Auto Documentation Generator

permissions:
  contents: write
  
on:
  push:
    branches:
      - feature 

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Graphviz (OS Level)
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz

    - name: Install Python Dependencies
      run: |
        pip install pydoc-markdown diagrams flasgger

    - name: Generate Code Docs
      run: |
        pydoc-markdown

    - name: Generate Architecture Diagram
      run: |
        python architecture.py

    - name: Commit Updated Docs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto update documentation" || echo "No changes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}